kind: pipeline
type: docker
name: checker

steps:
  - name: node-modules
    image: node:17
    commands:
      - npm ci
  - name: checkers
    image: node:17
    commands:
      - npm run eslint
      - npm run validate-configs

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
type: docker
name: latest-test

steps:
  - name: node-modules
    image: node:17
    commands:
      - npm ci
  - name: test-run-latest
    image: node:17
    commands:
      - npm run start -- build

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
type: docker
name: latest-krankerl-enabled-test

steps:
  - name: node-modules
    image: node:17
    commands:
      - npm ci
  - name: test-run-krankerl
    image: node:17
    commands:
      - npm run start -- build --exec-krankerl-cmds true > /dev/null 2>&1

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
type: docker
name: nc-20-test

steps:
  - name: node-modules
    image: node:17
    commands:
      - npm ci
  - name: test-run
    image: node:17
    commands:
      - npm run start -- build --nc-version v20.0.12

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
type: docker
name: nc-21-test

steps:
  - name: node-modules
    image: node:17
    commands:
      - npm ci
  - name: test-run
    image: node:17
    commands:
      - npm run start -- build --nc-version v21.0.4

trigger:
  branch:
    - master
  event:
    - pull_request
    - push

---
kind: pipeline
type: docker
name: master-build-test

steps:
  - name: node-modules
    image: node:17
    commands:
      - npm ci
  - name: test-run-master
    image: node:17
    commands:
      - npm run start -- build --nc-version master

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
